eef_rotation: {x: 0, y: 3.1415, z: 0}
left_eef: {home_pos: {x: 0.18, y: 0.6, z: 0.17}, initial_pos: {x: 0.65, y: 0.3, z: 0.14}}
right_eef: {home_pos: {x: 0.18, y: -0.6, z: 0.17}, initial_pos: {x: 0.65, y: -0.3, z: 0.14}}
min_wp_distance: 0.01 ## min dist between 2 cartesian wps
gripper_state: {left: 'close', right: 'middle'}
execute_traj_topic: '/baxter_kinematics/traj_exec_run'
feedback_topic: '/baxter_kinematics/traj_exec_info'
obj_moved_threshold: 0.03
env_changed: False
visual_type: "cloud" # "blob"