real_robot: True
eef_rotation: {x: 0, y: 3.1415, z: 0}
left_eef: {home_pos: {x: 0.18, y: 0.6, z: 0.17}, initial_pos: {x: 0.65, y: 0.3, z: 0.14}}
right_eef: {home_pos: {x: 0.18, y: -0.6, z: 0.17}, initial_pos: {x: 0.65, y: -0.3, z: 0.14}}
min_wp_distance: 0.01
gripper_state: {left: 'close', right: 'middle'}
feedback_topic: '/baxter_kinematics/traj_exec_info'
env_changed: False


